Schema erwin
Estete9/my-things-catalog pull request #37
Opened 2023-12-05 23:18 UTC by eamador1

The following changes were made in this branch:
---

- create tables item, music_album and genre in schema.sql

2023-12-05 23:55 UTC, Estete9 requested changes
Hi @eamador1 
I'll review this PR. ✋

Good job so far it looks quite good!
There are some recommendations I would like you to take into account.

Highlights
 You have written a clean code ✅
 The distribution, padding, and margins are perfect. ✅
 Good PR title/description ✅
Required Changes ♻️
 Good job adding the elements in the list in the main section, but we can improve it a little bit more together. 💪 
 
Check the comments under the review.

Cheers and Happy coding!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @Estete9 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/Estete9">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@Estete9" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/esteban-palacios-5030a772/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-esteban-palacios-5030a772" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@NaughTban" />
</a>

</td>
</tr>

2023-12-06 00:07 UTC, eamador1 commented
The following changes were made since the last code review:
---

- Delete item table and add inherited properties to music_album table

2023-12-06 01:38 UTC, Estete9 requested changes
Hi @eamador1 
I'll review this PR. ✋

Good job so far it looks quite good!
There are some recommendations I would like you to take into account.

<img src="https://media1.giphy.com/media/jTT8NCauGbsF3YDmXX/giphy.gif"/>

Highlights
 You have written a clean code ✅
 The distribution, padding, and margins are perfect. ✅
 Good PR title/description ✅
Required Changes ♻️
 Good job adding the elements in the list in the main section, but we can improve it a little bit more together. 💪 
 
Check the comments under the review.

Cheers and Happy coding!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @Estete9 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/Estete9">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@Estete9" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/esteban-palacios-5030a772/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-esteban-palacios-5030a772" />
</a>

</td>
<td>

<a href="https://twitter.com/NaughTban">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@NaughTban" />
</a>

</td>
</tr>

2023-12-06 02:33 UTC, Estete9 commented on schema.sql
> +);
Great job including the properties from the item class in the music_album table.
Please help me by adding some more properties to the table. We need to add the genre_id, author_id, and label_id.
Also please add the foreign keys with the references to the genres(id), authors(id), and labels(id)

Guide yourself with the `games` table implemented by Jose

2023-12-06 02:44 UTC, eamador1 commented
Since the last code review the following changes were made:
---

- add relation between music_album table and genre, label and author tables ✅

2023-12-06 02:47 UTC, Estete9 approved these changes
## Hi @eamador1  , 

Your feature is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

<img src="https://media1.giphy.com/media/nqi89GMgyT3va/giphy.gif"/>


## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Great use of modules ✅ 
- Linters are green ✅ 
- Meaningful **Github** commits ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @Estete9 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/Estete9">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@Estete9" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/esteban-palacios-5030a772/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-esteban-palacios-5030a772" />
</a>

</td>
<td>

<a href="https://twitter.com/NaughTban">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@NaughTban" />
</a>

</td>
</tr>
</table>

2023-12-06 02:47 UTC, merged